- 
  name: Installing Nginx and starting it 
  hosts: servers 
  become: yes 
  tasks: 
    - name: Installing Nginx 
      apt: 
        name: nginx 
        state: latest 
    - name: Starting Nginx 
      service: 
        name: nginx 
        state: started 
        enabled: yes

    - name: Deploying static webpage
      copy:
        src: index.html
        dest: /var/www/html